Add explicit note about vulnerability in this driver
oscarlab/graphene-sgx-driver pull request #20
Opened 2020-05-27 11:36 UTC by mkow

As correctly pointed out on LKML (["[PATCH v12 00/18] Enable FSGSBASE instructions" thread](https://lore.kernel.org/lkml/20200511045311.4785-1-sashal@kernel.org/)), we should be more explicit that this driver should be used only for testing or in dedicated VMs, because it introduces a local privilege escalation vuln. See the README diff for more info.

I'll also do a follow-up in the main repo.

2020-05-27 13:49 UTC, chiache approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/20)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/20#-M8LNq_f8i955ljK0W5b:-M8LNq_g5nhCZ6Z_ON0-:b-jy0vs4) (no related file):*
Looks good to me. Another suggestion: Maybe we should stop calling it the Graphene-SGX driver or gsgx driver, but giving it a more comprehensible name like "FSGSBASE_ROOTING" module?

---


<!-- Sent from Reviewable.io -->

2020-05-27 17:01 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/20)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @chiache)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/20#-M8LNq_f8i955ljK0W5b:-M8M3USGAgH8eMFiW_n6:b-qrbadq) (no related file):*
<details><summary><i>Previously, chiache (Chia-Che Tsai) wrote…</i></summary><blockquote>

Looks good to me. Another suggestion: Maybe we should stop calling it the Graphene-SGX driver or gsgx driver, but giving it a more comprehensible name like "FSGSBASE_ROOTING" module?
</blockquote></details>

"rooting"? I don't think this expresses what you wanted to say, at least in this context (driver name).
But I agree, the name is not adequate anymore after we removed everything except fsgsbase from it.

---


<!-- Sent from Reviewable.io -->

2020-05-28 17:05 UTC, donporter requested changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/20)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @chiache and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/20#-M8REcwxDiEmRzK2SELF:-M8REcwxDiEmRzK2SELG:b-81wkwn) (no related file):*
Weren't we going to add a taint?  Otherwise, LGTM

---


<!-- Sent from Reviewable.io -->

2020-05-28 17:06 UTC, donporter approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/20)* status: all files reviewed, 2 unresolved discussions (waiting on @chiache and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/20#-M8REcwxDiEmRzK2SELF:-M8REvY48-nSSLZN8bXu:bwwmlde) (no related file):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

Weren't we going to add a taint?  Otherwise, LGTM
</blockquote></details>

NM - my understanding is that TAINT_OOT is set automatically.

---


<!-- Sent from Reviewable.io -->

2020-05-28 17:07 UTC, boryspoplawski approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/20)* status: all files reviewed, 2 unresolved discussions (waiting on @chiache, @donporter, and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/20#-M8LNq_f8i955ljK0W5b:-M8REq5I9lEfw9v1Aq7M:b80vkej) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

"rooting"? I don't think this expresses what you wanted to say, at least in this context (driver name).
But I agree, the name is not adequate anymore after we removed everything except fsgsbase from it.
</blockquote></details>

+1 to renaming

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/20#-M8REcwxDiEmRzK2SELF:-M8REl9MCpP7u_MPbOJ6:bbytvsw) (no related file):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

Weren't we going to add a taint?  Otherwise, LGTM
</blockquote></details>

OOT module will taint the kernel anyway.

---


<!-- Sent from Reviewable.io -->

2020-05-28 17:15 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/20)* status: all files reviewed, 1 unresolved discussion (waiting on @donporter)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/20#-M8LNq_f8i955ljK0W5b:-M8RGELO1uoF2AbyUcbR:b4o0kq2) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

+1 to renaming
</blockquote></details>

Even if, this is something for another PR. But I'd leave it as is, hopefully this driver will be deprecated soon.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/20#-M8REcwxDiEmRzK2SELF:-M8RGh7D0q61t1wpnqtF:b-19m8jr) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

OOT module will taint the kernel anyway.
</blockquote></details>

Yup, see https://elixir.bootlin.com/linux/v5.6.15/source/kernel/module.c#L3085 (it's `TAINT_OOT_MODULE`, to be precise)

---


<!-- Sent from Reviewable.io -->

2020-05-28 17:15 UTC, donporter approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/20)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-06-08 13:45 UTC, merged