Add FSGSBASE patch backported to Linux kernel 5.4
oscarlab/graphene-sgx-driver pull request #26
Opened 2020-07-16 20:54 UTC by dimakuv

FSGSBASE support is not yet in the Linux kernel upstream. Due to the urgent need for this feature support for Graphene, this commit provides a patch set, backported to Linux 5.4, which is the long-term supported kernel version with critical security patches applied.

2020-07-17 00:01 UTC, mkow requested changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/26)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[fsgsbase_patches/fsgsbase_backport_5.4.y.tar, line 0 at r1](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/26#-MCP2k1l5d1h_yTjdifD:-MCP2k1l5d1h_yTjdifE:bn63zpk) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/02a580e1ca7cf0c068f147d9c94f06a8251b36b6/fsgsbase_patches/fsgsbase_backport_5.4.y.tar#L0)):*
Please don't submit binary blobs to the repo, this obfuscates diffs.
git already compresses the contents on its own, so I don't think there's any reason to submit these patches packed.


<!-- Sent from Reviewable.io -->

2020-07-17 16:47 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/26)* status: 1 of 18 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[fsgsbase_patches/fsgsbase_backport_5.4.y.tar, line  at r1](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/26#-MCP2k1l5d1h_yTjdifD:-MCSf61v9dI1R_dmDCCr:b-3io7r8) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/02a580e1ca7cf0c068f147d9c94f06a8251b36b6/fsgsbase_patches/fsgsbase_backport_5.4.y.tar#L)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please don't submit binary blobs to the repo, this obfuscates diffs.
git already compresses the contents on its own, so I don't think there's any reason to submit these patches packed.
</blockquote></details>

Done. Good point. Note that I rebased the whole PR instead of a fixup.


<!-- Sent from Reviewable.io -->

2020-07-20 19:01 UTC, mkow requested changes
> Reviewed 18 of 18 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/26)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/26#-MChYa8q7FsrqpBURyOE:-MChYa8r-ajvdtX4L_ys:brdjehr) (no related file):*
Could you write somewhere (README, I guess?) on which version of the upstream patchset this backport is based on? This will be useful for updating it (e.g. to include bugfixes from newer versions)

---


<!-- Sent from Reviewable.io -->

2020-07-20 19:21 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/26)* status: 17 of 18 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/26#-MChYa8q7FsrqpBURyOE:-MChf6Uq9l8GiwXQroiP:b-896fix) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you write somewhere (README, I guess?) on which version of the upstream patchset this backport is based on? This will be useful for updating it (e.g. to include bugfixes from newer versions)
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2020-07-20 19:24 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/26)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-07-20 20:31 UTC, yamahata submitted a review, later dismissed
> Reviewed 17 of 18 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/26)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-07-20 21:17 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/26)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2020-07-20 22:59 UTC, yamahata approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/26)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-07-20 23:00 UTC, merged