Allow to use the default C header of the in-kernel SGX driver
oscarlab/graphene-sgx-driver pull request #27
Opened 2020-08-03 21:58 UTC by dimakuv

This PR allows to use in-kernel Intel SGX driver. While building Graphene, the user must simply skip the prompt of the SGX driver's directory (by pressing ENTER).

This PR relies on the fact that the `ioctl` API of the Intel SGX driver v32+ doesn't change any more. So the PR simply uses the `sgx_in_kernel.h` copy-pasted from the in-kernel Intel SGX driver.

2020-08-04 00:23 UTC, yamahata submitted a review, later dismissed
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/27)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2020-08-12 17:07 UTC, mkow requested changes
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/27)* status: all files reviewed, 4 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[link-intel-driver.py, line 16 at r1](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/27#-MEYam4a1LSUzVFdeXiu:-MEYam4a1LSUzVFdeXiv:b-ojdi0j) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/c0d97968e10f3186fd9aede29eea96128b0e5ef0/link-intel-driver.py#L16)):*
> ```Python
>     Graphene only needs one header from the Intel SGX Driver:
>       - default sgx_in_kernel.h for in-kernel 32+ version of the driver
>         (https://lkml.org/lkml/2020/7/16/622)
> ```

I'd rather link to lore.kernel.org, it provides information how to get the patch sources. I think the corresponding link is https://lore.kernel.org/linux-sgx/20200716135303.276442-1-jarkko.sakkinen@linux.intel.com/T/#mad402d3d60cff299f3dbc14c622d2bf5f3992c18.
___
*[link-intel-driver.py, line 31 at r1](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/27#-MEYbaSeAt39GkDWSDWj:-MEYbaSeAt39GkDWSDWk:b5qnlxh) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/c0d97968e10f3186fd9aede29eea96128b0e5ef0/link-intel-driver.py#L31)):*
> ```Python
>         isgx_driver_path = os.path.expanduser(input(msg))
> 
>     if not isgx_driver_path or isgx_driver_path.strip() == "":
> ```

please use single quotes
___
*[README.rst, line 37 at r1](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/27#-MEYbruH1Le18Mq9Qd-Z:-MEYbruH1Le18Mq9Qd-_:b-7ropln) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/c0d97968e10f3186fd9aede29eea96128b0e5ef0/README.rst#L37)):*
> ```reStructuredText
> system. The supported versions of the Intel SGX driver are:
> 
> - In-kernel SGX driver, only versions 32+ (https://lkml.org/lkml/2020/7/16/622)
> ```

ditto
___
*[sgx_in_kernel.h, line 7 at r1](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/27#-MEYcOGw0i780zf1_UkN:-MEYcOGw0i780zf1_UkO:b-m2iup4) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/c0d97968e10f3186fd9aede29eea96128b0e5ef0/sgx_in_kernel.h#L7)):*
> ```objc
> #ifndef _UAPI_ASM_X86_SGX_H
> #define _UAPI_ASM_X86_SGX_H
> ```

Could you add a TODO here or somewhere else to delete this once the driver is upstreamed and the headers are distributed with the system?
___
*[sgx_in_kernel.h, line 107 at r1](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/27#-MEYcAuVAYGUX2a3SNkM:-MEYcAuVAYGUX2a3SNkN:b-hs4pe5) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/c0d97968e10f3186fd9aede29eea96128b0e5ef0/sgx_in_kernel.h#L107)):*
> ```objc
>  * @tcs:	Thread Control Structure used to enter enclave
>  * @ret:	0 on success (EEXIT), -EFAULT on an exception
>  * @e:		Pointer to struct sgx_enclave_exception (as provided by caller)
> ```

Do they really align everything with tabs? :(
Looks terrible in any setting different than theirs...


<!-- Sent from Reviewable.io -->

2020-08-12 17:21 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/27)* status: 0 of 3 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @yamahata)

___
*[link-intel-driver.py, line 16 at r1](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/27#-MEYam4a1LSUzVFdeXiu:-MEYfAHT7dpGXmR33rAu:b-896fix) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/c0d97968e10f3186fd9aede29eea96128b0e5ef0/link-intel-driver.py#L16)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd rather link to lore.kernel.org, it provides information how to get the patch sources. I think the corresponding link is https://lore.kernel.org/linux-sgx/20200716135303.276442-1-jarkko.sakkinen@linux.intel.com/T/#mad402d3d60cff299f3dbc14c622d2bf5f3992c18.
</blockquote></details>

Done.
___
*[link-intel-driver.py, line 31 at r1](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/27#-MEYbaSeAt39GkDWSDWj:-MEYfD2-EvkfBhevG-2n:b-896fix) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/c0d97968e10f3186fd9aede29eea96128b0e5ef0/link-intel-driver.py#L31)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please use single quotes
</blockquote></details>

Done.
___
*[README.rst, line 37 at r1](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/27#-MEYbruH1Le18Mq9Qd-Z:-MEYfbr63EKzqVLKLUTF:b-896fix) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/c0d97968e10f3186fd9aede29eea96128b0e5ef0/README.rst#L37)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[sgx_in_kernel.h, line 7 at r1](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/27#-MEYcOGw0i780zf1_UkN:-MEYg-5cDmT-wzs2XsWf:b-896fix) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/c0d97968e10f3186fd9aede29eea96128b0e5ef0/sgx_in_kernel.h#L7)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you add a TODO here or somewhere else to delete this once the driver is upstreamed and the headers are distributed with the system?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-08-12 18:56 UTC, mkow submitted a review, later dismissed
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/27)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-08-12 19:05 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/27)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-08-12 20:18 UTC, merged