graphene-sgx.h: compatibility for 1.9
oscarlab/graphene-sgx-driver pull request #3
Opened 2018-12-04 00:42 UTC by yamahata

This patch make it build with 1.9 with SGX_INVALID_EINITTOKEN.
It was renamed from SGX_INVALID_LICENSE to SGX_INVALID_EINITTOKEN.
the define is protected with version 2.1, but it causes 1.9 build
breakage. Remove version check.

Signed-off-by: Isaku Yamahata <isaku.yamahata@gmail.com>

2018-12-06 23:40 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/3)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chiache)



<!-- Sent from Reviewable.io -->

2019-01-10 18:56 UTC, dimakuv commented
Could we lend this patch? Many people run into this issue when trying to build Graphene-SGX.

2019-03-12 01:58 UTC, yamahata commented
ping? any objection or can we proceed?

2019-03-12 18:58 UTC, chiache requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/3)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @yamahata)

___
*[graphene-sgx.h, line 41 at r1](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/3#-L_nFIZt8iSDdUmTTTPZ:-L_nFIZu5hMHeclAfprl:bvriywb) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/2e1ab0d99076739da8a13d01fb9a155e13ab73ab/graphene-sgx.h#L41)):*
> ```objc
> #endif
> 
> #else // SDK_DRIVER_VERSION < KERNEL_VERSION(1, 8, 0)
> ```

Missing the pairing `#if` directive. This line needs to be changed to: `#if SDK_DRIVER_VERSION < KERNEL_VERSION(1, 8, 0)`.

Also, you can remove the following `#include` directive.


<!-- Sent from Reviewable.io -->

2019-03-13 00:50 UTC, yamahata reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/3)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @chiache)

___
*[graphene-sgx.h, line 41 at r1](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/3#-L_nFIZt8iSDdUmTTTPZ:-L_oW1Ya-yDMnbzb-8uF:b-tn5j4j) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/2e1ab0d99076739da8a13d01fb9a155e13ab73ab/graphene-sgx.h#L41)):*
<details><summary><i>Previously, chiache (Chia-Che Tsai) wrote…</i></summary><blockquote>

Missing the pairing `#if` directive. This line needs to be changed to: `#if SDK_DRIVER_VERSION < KERNEL_VERSION(1, 8, 0)`.

Also, you can remove the following `#include` directive.
</blockquote></details>

The pairing #if directive is the one, "#if SDK_DRIVER_VERSION >= KERNEL_VERSION(1, 9, 0)".
The deleted one, "if SDK_DRIVER_VERSION >= KERNEL_VERSION(2, 1, 0)" is replaced with "#ifndef SGX_INVALID_LICENSE"


<!-- Sent from Reviewable.io -->

2019-08-01 22:11 UTC, chiache approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/3)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[graphene-sgx.h, line 41 at r1](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/3#-L_nFIZt8iSDdUmTTTPZ:-LlEE64c0Yhol-8s2WeR:b-r9sco) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/2e1ab0d99076739da8a13d01fb9a155e13ab73ab/graphene-sgx.h#L41)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

The pairing #if directive is the one, "#if SDK_DRIVER_VERSION >= KERNEL_VERSION(1, 9, 0)".
The deleted one, "if SDK_DRIVER_VERSION >= KERNEL_VERSION(2, 1, 0)" is replaced with "#ifndef SGX_INVALID_LICENSE"
</blockquote></details>

Sorry, my mistake.


<!-- Sent from Reviewable.io -->

2019-08-01 23:31 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/3)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-08-02 05:59 UTC, merged