Remove support for older DCAP/in-kernel drivers that use /dev/sgx
oscarlab/graphene-sgx-driver pull request #30
Opened 2020-10-30 09:35 UTC by dimakuv

DCAP SGX drivers v1.5- and in-kernel SGX drivers v19- use SGX device `/dev/sgx` instead of of the newer `/dev/sgx/enclave`. Nobody uses these old versions these days, so remove support for them.

2020-10-31 01:53 UTC, mkow approved these changes
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/30)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2020-10-31 01:55 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/30)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/30#-MKwMRKd7c5UfkW4D82G:-MKwMRKe7hNLYHTBBAbc:b-2s1ln2) (no related file):*
From the commit message:

> instead of of the newer

Please fix this :)

---


<!-- Sent from Reviewable.io -->

2020-11-02 08:43 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/30)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/30#-MKwMRKd7c5UfkW4D82G:-ML76tMU05sqxUKfsiWC:b-j9zbza) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

From the commit message:

> instead of of the newer

Please fix this :)
</blockquote></details>

Done. Force-pushed.

---


<!-- Sent from Reviewable.io -->

2020-11-02 17:49 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/30)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2020-11-02 18:41 UTC, boryspoplawski approved these changes
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/30)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-02 19:01 UTC, yamahata approved these changes
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/30)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-03 00:36 UTC, merged