Add DCAP functions
oscarlab/graphene-sgx-driver pull request #7
Opened 2019-09-06 06:51 UTC by ian0371

This is related to [this PR](https://github.com/oscarlab/graphene/pull/978).
`link-intel-driver.py` checks if the given SGX driver is DCAP, and if so, `SGX_DCAP` is defined.

Also, `load.sh` runs different code depending on whether the driver is DCAP or not.

2019-09-06 16:32 UTC, dimakuv approved these changes
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/7)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2019-09-06 16:37 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/7)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @ian0371)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/7#-Lo6QAtR5_wekYpw6MkD:-Lo6QAtR5_wekYpw6MkE:bqlb2lo) (no related file):*
What about this patch that you mentioned in https://github.com/oscarlab/graphene/pull/978 ?
```
--- a/gsgx_ioctl_1_7.c
+++ b/gsgx_ioctl_1_7.c
@@ -75,7 +75,10 @@ static long enclave_init(struct file *filep, void * arg)
 
 	isgx_init.addr = initp->addr;
 	isgx_init.sigstruct = initp->sigstruct;
+
+#ifndef SGX_DCAP
 	isgx_init.einittoken = initp->einittoken;
+#endif
...
```

---


<!-- Sent from Reviewable.io -->

2019-09-06 17:26 UTC, yamahata reviewed
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/7)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @ian0371)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/7#-Lo6QAtR5_wekYpw6MkD:-Lo6aTIf6qtzA3hCPexz:b32v57) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What about this patch that you mentioned in https://github.com/oscarlab/graphene/pull/978 ?
```
--- a/gsgx_ioctl_1_7.c
+++ b/gsgx_ioctl_1_7.c
@@ -75,7 +75,10 @@ static long enclave_init(struct file *filep, void * arg)
 
 	isgx_init.addr = initp->addr;
 	isgx_init.sigstruct = initp->sigstruct;
+
+#ifndef SGX_DCAP
 	isgx_init.einittoken = initp->einittoken;
+#endif
...
```
</blockquote></details>

+1

---
___
*[link-intel-driver.py, line 83 at r1](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/7#-Lo6aHd-8T67RNPouij5:-Lo6aHd-8T67RNPouij6:b-4abygk) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/b8a3d67a0fba9d79142c46ed97cafaea36cc94a9/link-intel-driver.py#L83)):*
> ```Python
>                               str(isgx_version_minor) + '"'
>         if dcap_driver:
>             print >> versionfile, '#define SGX_DCAP'
> ```

For get-token, "#define SGX_DCAP 1"


<!-- Sent from Reviewable.io -->

2019-09-08 10:52 UTC, ian0371 reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/7)* status: 5 of 8 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/7#-Lo6QAtR5_wekYpw6MkD:-LoFV6gX2wWlcqdOKn1x:b-6rgnny) (no related file):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done. Completely forgot about it. Updated `gsgx_ioctl_1_6.c` as well.

---
___
*[link-intel-driver.py, line 83 at r1](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/7#-Lo6aHd-8T67RNPouij5:-LoFVGFF1RxFhC-mClxG:b-896fix) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/b8a3d67a0fba9d79142c46ed97cafaea36cc94a9/link-intel-driver.py#L83)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

For get-token, "#define SGX_DCAP 1"
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-09-08 16:31 UTC, yamahata reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/7)* status: 5 of 8 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @ian0371, and @yamahata)

___
*[graphene-sgx.h, line 69 at r2](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/7#-LoGhMyhCaW2QtyuZa6D:-LoGhMyhCaW2QtyuZa6E:b9rrt60) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/85283a6cae1343540975306db453aaff44cee5c3/graphene-sgx.h#L69)):*
> ```objc
> 	uint64_t addr;
> 	uint64_t sigstruct;
> #ifndef SGX_DCAP
> ```

einittoken should be kept for abi compatibility.


<!-- Sent from Reviewable.io -->

2019-09-09 03:57 UTC, ian0371 reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/7)* status: 4 of 7 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @yamahata)

___
*[graphene-sgx.h, line 69 at r2](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/7#-LoGhMyhCaW2QtyuZa6D:-LoJ9tHf4GgegQU3Tbtk:b-896fix) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/85283a6cae1343540975306db453aaff44cee5c3/graphene-sgx.h#L69)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

einittoken should be kept for abi compatibility.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-09-10 14:53 UTC, dimakuv approved these changes
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/7)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2020-02-13 00:52 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/7)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @ian0371)

___
*[.gitignore, line 12 at r3](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/7#-M-w0ScLECx6cbw2VNI6:-M-w0ScLECx6cbw2VNI7:b-smiuv9) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/9cfc28a7dce9db62660cc9bf40ecf962d1151461/.gitignore#L12)):*
> ```ignore
> linux-sgx-driver
> isgx_version.h
> load.sh
> ```

https://github.com/oscarlab/graphene-sgx-driver/pull/12 removes this file completely. It is useless.
___
*[gsgx_ioctl_1_6.c, line 85 at r3](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/7#-M-w0WVu-wkCGX8SRX_U:-M-w0WVu-wkCGX8SRX_V:bfdp238) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/9cfc28a7dce9db62660cc9bf40ecf962d1151461/gsgx_ioctl_1_6.c#L85)):*
> ```C
> #ifndef SGX_DCAP
> 	isgx_init.einittoken = (struct isgx_einittoken *) initp->einittoken;
> #endif
> ```

https://github.com/oscarlab/graphene-sgx-driver/pull/12 removes this file completely.
___
*[gsgx_ioctl_1_7.c, line 81 at r3](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/7#-M-w0Y6x7-y4HBGPvXJe:-M-w0Y6x7-y4HBGPvXJf:bfdp238) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/9cfc28a7dce9db62660cc9bf40ecf962d1151461/gsgx_ioctl_1_7.c#L81)):*
> ```C
> #ifndef SGX_DCAP
> 	isgx_init.einittoken = initp->einittoken;
> #endif
> ```

https://github.com/oscarlab/graphene-sgx-driver/pull/12 removes this file completely.
___
*[link-intel-driver.py, line 69 at r3](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/7#-M-w0av3B1PoXX813viI:-M-w0av3B1PoXX813viJ:b-z0uct1) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/9cfc28a7dce9db62660cc9bf40ecf962d1151461/link-intel-driver.py#L69)):*
> ```Python
>         with open(sgx_main_path, 'r') as f:
>             if 'X86_FEATURE_SGX_LC' in f.read():
>                 dcap_driver = True
> ```

This should be slightly rewritten after https://github.com/oscarlab/graphene-sgx-driver/pull/12 is merged.
___
*[link-intel-driver.py, line 83 at r3](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/7#-M-w0hhv1wjNxBJbUrpy:-M-w0hhwCk8dryCLhNkq:b4q1ywv) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/9cfc28a7dce9db62660cc9bf40ecf962d1151461/link-intel-driver.py#L83)):*
> ```Python
>                               str(isgx_version_minor) + '"'
>         if dcap_driver:
>             print >> versionfile, '#define SGX_DCAP 1'
> ```

We won't have `isgx_version.h` after we merge https://github.com/oscarlab/graphene-sgx-driver/pull/12. Instead, all such defines must be added to `sgx.h`.
___
*[link-intel-driver.py, line 91 at r3](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/7#-M-w0pBcESmRhwmsdFzZ:-M-w0pBcESmRhwmsdFz_:b-x4lxc0) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/9cfc28a7dce9db62660cc9bf40ecf962d1151461/link-intel-driver.py#L91)):*
> ```Python
>             print >> loadsh, 'load_sgx_dcap_driver'
>         else:
>             print >> loadsh, 'load_sgx_driver'
> ```

We won't have `load.sh`, so this won't be needed.
___
*[load_func.sh, line 19 at r3](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/7#-M-w0siB6nC6wJTfiGL0:-M-w0siB6nC6wJTfiGL1:b-24v4b) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/9cfc28a7dce9db62660cc9bf40ecf962d1151461/load_func.sh#L19)):*
> ```Shell
>     sudo modprobe intel_sgx || exit -1
>     sudo insmod graphene-sgx.ko || exit -1
> }
> ```

This whole file won't be needed after https://github.com/oscarlab/graphene-sgx-driver/pull/12 is merged.
___
*[Makefile, line 26 at r3](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/7#-M-w0vrx4IqchNooUfp1:-M-w0vrx4IqchNooUfp2:b-2vi2gy) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/9cfc28a7dce9db62660cc9bf40ecf962d1151461/Makefile#L26)):*
> ```Makefile
> .PHONY: clean
> clean:
> 	rm -vrf linux-sgx-driver isgx_version.h load.sh
> ```

`load.sh` will be completely removed once https://github.com/oscarlab/graphene-sgx-driver/pull/12 is merged.


<!-- Sent from Reviewable.io -->

2020-02-15 13:05 UTC, ian0371 reviewed
It's become much simpler. Please take a look.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/7#-:-M07wbND4lFdR-IviqNb:b83qkvt)* status: 0 of 1 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[.gitignore, line 12 at r3](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/7#-M-w0ScLECx6cbw2VNI6:-M07wXQi2LWxUVGd67sW:b-896fix) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/9cfc28a7dce9db62660cc9bf40ecf962d1151461/.gitignore#L12)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

https://github.com/oscarlab/graphene-sgx-driver/pull/12 removes this file completely. It is useless.
</blockquote></details>

Done.
___
*[gsgx_ioctl_1_6.c, line 85 at r3](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/7#-M-w0WVu-wkCGX8SRX_U:-M07wY9V60ZpNz7R8Cs3:b-896fix) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/9cfc28a7dce9db62660cc9bf40ecf962d1151461/gsgx_ioctl_1_6.c#L85)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

https://github.com/oscarlab/graphene-sgx-driver/pull/12 removes this file completely.
</blockquote></details>

Done.
___
*[gsgx_ioctl_1_7.c, line 81 at r3](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/7#-M-w0Y6x7-y4HBGPvXJe:-M07wYZ11JJ_vFnV_Ch3:b-896fix) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/9cfc28a7dce9db62660cc9bf40ecf962d1151461/gsgx_ioctl_1_7.c#L81)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

https://github.com/oscarlab/graphene-sgx-driver/pull/12 removes this file completely.
</blockquote></details>

Done.
___
*[link-intel-driver.py, line 69 at r3](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/7#-M-w0av3B1PoXX813viI:-M07wZ5B5a9Ox7BVks6D:b-896fix) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/9cfc28a7dce9db62660cc9bf40ecf962d1151461/link-intel-driver.py#L69)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This should be slightly rewritten after https://github.com/oscarlab/graphene-sgx-driver/pull/12 is merged.
</blockquote></details>

Done.
___
*[link-intel-driver.py, line 83 at r3](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/7#-M-w0hhv1wjNxBJbUrpy:-M07wZXiBn89EjXpggE_:b-896fix) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/9cfc28a7dce9db62660cc9bf40ecf962d1151461/link-intel-driver.py#L83)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We won't have `isgx_version.h` after we merge https://github.com/oscarlab/graphene-sgx-driver/pull/12. Instead, all such defines must be added to `sgx.h`.
</blockquote></details>

Done.
___
*[link-intel-driver.py, line 91 at r3](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/7#-M-w0pBcESmRhwmsdFzZ:-M07w_0KBxxHHTfxXg8B:b-896fix) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/9cfc28a7dce9db62660cc9bf40ecf962d1151461/link-intel-driver.py#L91)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We won't have `load.sh`, so this won't be needed.
</blockquote></details>

Done.
___
*[load_func.sh, line 19 at r3](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/7#-M-w0siB6nC6wJTfiGL0:-M07w_UOA-fucxg_cvwW:b-896fix) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/9cfc28a7dce9db62660cc9bf40ecf962d1151461/load_func.sh#L19)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This whole file won't be needed after https://github.com/oscarlab/graphene-sgx-driver/pull/12 is merged.
</blockquote></details>

Done.
___
*[Makefile, line 26 at r3](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/7#-M-w0vrx4IqchNooUfp1:-M07wa-T6n2rPpKcdWmX:b-896fix) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/9cfc28a7dce9db62660cc9bf40ecf962d1151461/Makefile#L26)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`load.sh` will be completely removed once https://github.com/oscarlab/graphene-sgx-driver/pull/12 is merged.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-02-18 21:25 UTC, dimakuv submitted a review, later dismissed
> Reviewed 6 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/7)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2020-02-20 23:41 UTC, yamahata approved these changes
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/7)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2020-02-20 23:41 UTC, yamahata submitted a review, later dismissed
> Reviewed 1 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/7)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2020-04-06 01:09 UTC, mkow requested changes
> Reviewed 1 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/7)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @ian0371)

___
*[link-intel-driver.py, line 41 at r4](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/7#-M4BwoLNBSWY9USI2tz_:-M4BwoLNBSWY9USI2tza:b-mu480o) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/e0d4075d75b8096024f192a1499353773704c63a/link-intel-driver.py#L41)):*
> ```Python
>     with open(this_header_path, 'a') as f:
>         f.write('\n\n#ifndef ISGX_FILE\n#define ISGX_FILE "%s"\n#endif\n' % dev_path)
>         if dev_path == '/dev/sgx':
> ```

Please add a comment saying that this works only until version 1.5 of DCAP driver (the driver structure has changed since then). See https://reviewable.io/reviews/oscarlab/graphene/978#-M4Bseu09PdqvshxfUn5.


<!-- Sent from Reviewable.io -->

2020-04-06 21:45 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/7)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[link-intel-driver.py, line 41 at r4](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/7#-M4BwoLNBSWY9USI2tz_:-M4GS4Ux2xvC6OyMzQ4-:b-rdhxcy) ([raw file](https://github.com/oscarlab/graphene-sgx-driver/blob/e0d4075d75b8096024f192a1499353773704c63a/link-intel-driver.py#L41)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please add a comment saying that this works only until version 1.5 of DCAP driver (the driver structure has changed since then). See https://reviewable.io/reviews/oscarlab/graphene/978#-M4Bseu09PdqvshxfUn5.
</blockquote></details>

Done in README.


<!-- Sent from Reviewable.io -->

2020-04-06 22:01 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-sgx-driver/7)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-04-07 17:20 UTC, merged